### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by clmbmb** [ftrvxmtrx/unflac#1]
Just found your program and tested it. For the most basic thing it works perfectly, but I'd like to:

1. Be able to set export dir and export the files directly there. At the moment your app creates Artist/Album/ directories and saves the files inside. No problem for me in fact, but sometimes it's nice to be able to save the files where I want.

2. Have the possibility to spevify cue file with different name than the flac. I had the situation that my cue file name was not capitalized as the flac file, so unflac was unable to do its thing.

**Comment by ftrvxmtrx** [comment]
Hi, regarding the first one, if I understood it correctly, there is `-o` option that specifies output directory for the exported files. Re second one, I'm working on making unnflac parse cue files first, and take out the audio filenames out of it instead of only relying on 1-1 matching audio and cue file names. It should also make multi-disk scenario work correctly.

**Comment by ftrvxmtrx** [comment]
2. hopefully fixed by d3a1be29e7fea4d88b94675eb2bb207fdb5a72a5

**Comment by clmbmb** [comment]
@ftrvxmtrx for 1. I checked again, -o doesn't do what I want/explained: I'd like to save the resulting files in the current directory, but without creating ARTIST/ALBUM subdirectory.

Example of what I have:
```
$ unflac -o . NI\ -\ 2015\ -\ Les\ Insurges\ de\ Romilly\ \[Dur\ et\ Doux\,\ DD-010\].flac 
NI/2015 - Les Insurges de Romilly/01 - Bouif.flac
NI/2015 - Les Insurges de Romilly/02 - Cuistre.flac
NI/2015 - Les Insurges de Romilly/03 - Rodomont.flac
NI/2015 - Les Insurges de Romilly/04 - Butor.flac
NI/2015 - Les Insurges de Romilly/05 - Marpaud.flac
NI/2015 - Les Insurges de Romilly/06 - Flaquadin.flac
NI/2015 - Les Insurges de Romilly/07 - Gringuenaudes.flac
NI/2015 - Les Insurges de Romilly/08 - Torfesor.flac
```

As you can see, it created a new directory, named NI/2015 - Les Insur...

```
$ tree
.
├── folder.jpg
├── NI
│   └── 2015 - Les Insurges de Romilly
│       ├── 01 - Bouif.flac
│       ├── 02 - Cuistre.flac
│       ├── 03 - Rodomont.flac
│       ├── 04 - Butor.flac
│       ├── 05 - Marpaud.flac
│       ├── 06 - Flaquadin.flac
│       ├── 07 - Gringuenaudes.flac
│       └── 08 - Torfesor.flac
├── NI - 2015 - Les Insurges de Romilly [Dur et Doux, DD-010].cue
├── NI - 2015 - Les Insurges de Romilly [Dur et Doux, DD-010].flac
├── NI - 2015 - Les Insurges de Romilly [Dur et Doux, DD-010].log
```

But I want the resulting flac files in my current folder.

**Comment by ftrvxmtrx** [comment]
Ah I see. In the newest version I added `-n` option to specify output file naming. Try `./unflac -n '{{printf .Input.TrackNumberFmt .Track.Number}} - {{.Track.Title | Elem}}' ......`
