### ISSUE TITLE
Unknown command 'fLaC"±:"'

### ISSUE THREAD

**Issue by clmbmb** [ftrvxmtrx/unflac#3]
Just updated with 'go get -u' and trying to split a new flac I got

    2019/10/11 12:06:28 Name_Of_File.flac: Line 1. Unknown command 'fLaC"±:"'.

And on a different (older) file:

    2019/10/11 12:08:29 Atnother_File.flac: Line 1. Unknown command 'fLaC"8'.

**Comment by ftrvxmtrx** [comment]
It's now either a directory or a cue sheet that needs to be specified as an input. I've just made some additional changes to make this more apparent in the help message.
