### ISSUE TITLE
Line 10. 00:00:00 time value expected.

### ISSUE THREAD

**Issue by lev777** [ftrvxmtrx/unflac#5]
unflacing the cue:
REM GENRE "Electronic, Classical"
REM DATE 2018
CATALOG 90210
PERFORMER "Bubba"
TITLE "Bubba Sings For You"
FILE "side1.flac" WAVE
  TRACK 01 AUDIO
    TITLE "The Voice Of Bubba"
    PERFORMER "Bubba"
    INDEX 01 00:05:00
<snip>

Behavior:
unflac fails with error - Line 10. 00:00:00 time value expected.

Expected behavior:
unflac could include a flag to allow execution to assume INDEX 00 00:00:00 for poorly constructed cue files when the first track is missing this statement or at least offer to assume INDEX 00 00:00:00 interactively rather than failing and requiring cue editing.

Other information:
foobar2000 has no issue with the cue file missing the INDEX 00 00:00:00 statement.

**Comment by ftrvxmtrx** [comment]
Fixed with the latest change to one of unflac's dependencies, do a `go get -u github.com/ftrvxmtrx/unflac`. It will still print a warning message but won't stop.
