### ISSUE TITLE
ffmpeg arg parsing 

### ISSUE THREAD

**Issue by lev777** [ftrvxmtrx/unflac#6]
Attempting to pass arg compression_level 8 for flac

ex. (works)
ffmpeg -i test.flac -compression_level 8 out.flac

unflac seems to have a problem parsing the arg list

"-arg-ffmpeg compression_level 8"
gives
flag provided but not defined: -arg-ffmpeg compression_level 8

-arg-ffmpeg compression_level 8
gives
CreateFile 8: The system cannot find the file specified.

-arg-ffmpeg "compression_level 8"
gives
Unable to find a suitable output format for 'compression_level 8'

Seems like first option should work according to Unflac help text:
_Usage of unflac
  -arg-ffmpeg value
        Add an argument to ffmpeg. Example: "-arg-ffmpeg -qscale:a --arg-ffmpeg 2"_

**Comment by ftrvxmtrx** [comment]
You have to pass `-arg-ffmpeg` before _every_ argument that ffmpeg needs. So it'd be `-arg-ffmpeg compression_level -arg-ffmpeg 8`.

**Comment by lev777** [comment]
-arg-ffmpeg compression_level -arg-ffmpeg 8
gives
Unable to find a suitable output format for 'compression_level'
compression_level: Invalid argument

"-arg-ffmpeg compression_level -arg-ffmpeg 8"
gives
flag provided but not defined: -arg-ffmpeg compression_level -arg-ffmpeg 8

"-arg-ffmpeg compression_level" "-arg-ffmpeg 8"
gives
flag provided but not defined: -arg-ffmpeg compression_level

**Comment by ftrvxmtrx** [comment]
I missed the dash there right before compression_level, sorry, `-arg-ffmpeg -compression_level -arg-ffmpeg 8`

**Comment by lev777** [comment]
Ah ha!  That works 👍 Thanks!
